// ======================================================================
// CUDA litmus test: MP-cluster-F
// Generated by HetLitmus CudaLang from a LISA/Bell scoped test.
// DO NOT EDIT -- regenerate via hetlitmus/emit-cuda.sh
//
// LISA source program:
//   P0: w[relaxed,cluster] x 1
//   P0: w[release,cluster] y 1
//   P1: r[acquire,cluster] r0 y
//   P1: r[relaxed,cluster] r1 x
// scopes: (sys (gpu (cluster (cta 0) (cta 1))))
// condition: exists (1:r0=1 /\ 1:r1=0)
// launch: <<<2, 1>>>  (2 CTA(s), 1 thread(s)/CTA)
// ======================================================================

#include <cuda/atomic>
#include <cstdio>

__global__ void litmus_MP_cluster_F(int* x, int* y, int* __out) {
  // ---- P0  (CTA 0, lane 0) ----
  if (blockIdx.x == 0 && threadIdx.x == 0) {
    { // w[relaxed,cluster] x 1
      asm volatile("st.relaxed.cluster.b32 [%0],%1;" :: "l"(x), "r"(1) : "memory"); // sm_90
    }
    { // w[release,cluster] y 1
      asm volatile("st.release.cluster.b32 [%0],%1;" :: "l"(y), "r"(1) : "memory"); // sm_90
    }
  }

  // ---- P1  (CTA 1, lane 0) ----
  if (blockIdx.x == 1 && threadIdx.x == 0) {
    int r0 = 0;
    int r1 = 0;
    { // r[acquire,cluster] r0 y
      asm volatile("ld.acquire.cluster.b32 %0,[%1];" : "=r"(r0) : "l"(y) : "memory"); // sm_90
    }
    { // r[relaxed,cluster] r1 x
      asm volatile("ld.relaxed.cluster.b32 %0,[%1];" : "=r"(r1) : "l"(x) : "memory"); // sm_90
    }
    __out[1 * 4 + 0] = r0;
    __out[1 * 4 + 1] = r1;
  }
}

// ---- host harness (illustrative; emit-only, not compiled here) ----
// Result buffer layout: __out[proc * 4 + regIndex].
// Reset all globals to 0 before each launch; the weak outcome under
// test is exactly the `condition' line above.
int main(void) {
  int *x;   cudaMallocManaged(&x, sizeof(int));
  int *y;   cudaMallocManaged(&y, sizeof(int));
  int *__out; cudaMallocManaged(&__out, sizeof(int) * 2 * 4);
  for (int it = 0; it < 100000; ++it) {
    *x = 0;
    *y = 0;
    litmus_MP_cluster_F<<<2, 1>>>(x, y, __out);
    cudaDeviceSynchronize();
    // TODO(hardware, Task 9): tally __out against the condition.
  }
  return 0;
}
