#!/usr/bin/env bash
# HetLitmus Layer-2 GOLDEN GATE (corpus + emission regression).
#
# See hetlitmus/docs/TEST-PLAN.md sections 2 ("Coverage map"), 4 ("Layer 2 -
# Generate") and 7 ("Golden & promote model").  This is the "no regression"
# guarantee for the generator/emitter black box: pin what the tools produce
# today and shout on ANY drift.  It needs NO nvcc/clang and NO GPU -- it is a
# pure regenerate + emit + text-diff over the committed corpus.
#
# What it does (return 0 only if ALL of corpus / census / emission are clean):
#   1. Corpus regression -- regenerate BOTH corpora in place (byte-stable) and
#      assert `git status --porcelain` over the two test dirs is empty, catching
#      add / remove / modify (a bare `git diff` would miss added/removed files).
#      A pre-existing working-tree edit is snapshotted BEFORE regen, because
#      regen overwrites (and would silently clobber) a hand-edit to a
#      grid-generated .litmus.
#   2. Census tripwire -- exactly 137 gpu-only + 411 het .litmus (the grid did
#      not silently shrink or grow).
#   3. Emission golden -- emit every gpu-only .cu to a TEMP dir and byte-diff the
#      10 committed cuda-out/*.cu samples against it.  emit-cuda.sh drops all 137
#      .cu (plus C-runtime boilerplate); emitting to a temp dir keeps cuda-out/
#      pristine (in-place would litter 127 untracked .cu).
#
# Non-destructive: regen is in place but byte-stable, emission uses a temp dir
# (auto-cleaned).  After a clean run the working tree is unchanged.
#
# Promote (when a change to the tools is intended): review `git diff`, then
#   - corpus:   regenerate + `git commit` the new .litmus (TEST-PLAN.md sect 7).
#   - emission: re-emit the 10 samples into cuda-out/ + `git commit`.
#
# Usage:  hetlitmus/verify/corpus-gate.sh        (no args)
# Exit:   0 = PASS, 1 = drift (offending paths/diffs printed), 2 = infra error.

set -uo pipefail   # NOT -e: we run every check and aggregate, not fail-fast.

# --- locate repo (hetlitmus/verify/ -> hetlitmus/ -> repo root) --------------
. "$(dirname "${BASH_SOURCE[0]}")/../paths.sh"
cd "$REPO"

export PATH="$BIN:$PATH"          # generate.sh resolves tools via $REPO/_build,
                                  # but keep PATH set for any bare-name callers.

GPU_DIR="hetlitmus/tests/gpu-only"
HET_DIR="hetlitmus/tests/het"
CUDA_OUT="hetlitmus/cuda-out"
EXPECT_GPU=137
EXPECT_HET=411

fail=0

# --- toolchain guard ---------------------------------------------------------
for b in diyone7 hetgen7 litmus7; do
  if [ ! -e "$BIN/$b" ]; then
    echo "FATAL: $BIN/$b not built -- run 'make all' in $REPO" >&2
    exit 2
  fi
done

# --- scratch (auto-cleaned so the tree stays pristine) -----------------------
EMITTMP="$(mktemp -d "${TMPDIR:-/tmp}/hetlitmus-gate.XXXXXX")"
cleanup() { rm -rf "$EMITTMP"; }
trap cleanup EXIT

echo "HetLitmus Layer-2 golden gate  (repo: $REPO)"
echo "=================================================================="

# ---------------------------------------------------------------------------
# 1. CORPUS REGRESSION  (regenerate in place; porcelain must be empty)
# ---------------------------------------------------------------------------
echo "[1/3] Corpus regression (regenerate + git porcelain)"

pre="$(git status --porcelain -- "$GPU_DIR" "$HET_DIR")"
if [ -n "$pre" ]; then
  # Uncommitted edit already present.  Do NOT regenerate: regen would overwrite
  # (clobber) a hand-edited grid test and mask the drift.
  echo "  FAIL: corpus has uncommitted changes (tamper / stale golden):"
  printf '%s\n' "$pre" | sed 's/^/        /'
  echo "        restore with: git checkout -- $GPU_DIR $HET_DIR"
  fail=1
else
  glog="$EMITTMP/generate.log"
  if ! bash "$GPU_DIR/generate.sh" >"$glog" 2>&1; then
    echo "FATAL: $GPU_DIR/generate.sh failed:" >&2; cat "$glog" >&2; exit 2
  fi
  if ! bash "$HET_DIR/generate.sh" >"$glog" 2>&1; then
    echo "FATAL: $HET_DIR/generate.sh failed:" >&2; cat "$glog" >&2; exit 2
  fi
  post="$(git status --porcelain -- "$GPU_DIR" "$HET_DIR")"
  if [ -n "$post" ]; then
    echo "  FAIL: regeneration diverged from the committed corpus (tool drift):"
    printf '%s\n' "$post" | sed 's/^/        /'
    echo "        review 'git diff -- $GPU_DIR $HET_DIR', then commit if intended."
    fail=1
  else
    echo "  PASS: both corpora regenerated byte-identical to HEAD (porcelain clean)"
  fi
fi

# ---------------------------------------------------------------------------
# 2. CENSUS  (the grid did not silently change size)
# ---------------------------------------------------------------------------
echo "[2/3] Census (.litmus counts)"
n_gpu=$(find "$GPU_DIR" -maxdepth 1 -name '*.litmus' | wc -l | tr -d ' ')
n_het=$(find "$HET_DIR" -maxdepth 1 -name '*.litmus' | wc -l | tr -d ' ')
echo "        gpu-only: $n_gpu .litmus (expect $EXPECT_GPU)"
echo "        het:      $n_het .litmus (expect $EXPECT_HET)"
if [ "$n_gpu" = "$EXPECT_GPU" ] && [ "$n_het" = "$EXPECT_HET" ]; then
  echo "  PASS: census $EXPECT_GPU + $EXPECT_HET"
else
  echo "  FAIL: census mismatch (expected $EXPECT_GPU + $EXPECT_HET)"
  fail=1
fi

# ---------------------------------------------------------------------------
# 3. EMISSION GOLDEN  (committed cuda-out/*.cu re-emit byte-identical)
# ---------------------------------------------------------------------------
echo "[3/3] Emission golden (committed cuda-out/*.cu)"
elog="$EMITTMP/emit.log"
if ! bash "$HETL/emit-cuda.sh" "$EMITTMP" >"$elog" 2>&1; then
  echo "FATAL: emit-cuda.sh failed:" >&2; cat "$elog" >&2; exit 2
fi

committed_cu="$(git ls-files "$CUDA_OUT/*.cu")"
total=0; match=0; emit_fail=0
for cu in $committed_cu; do
  total=$((total + 1))
  base="$(basename "$cu")"
  if [ ! -f "$EMITTMP/$base" ]; then
    echo "  DRIFT: $base is committed but emit-cuda.sh did not produce it"
    emit_fail=1
    continue
  fi
  if diff -u "$cu" "$EMITTMP/$base" >"$EMITTMP/diff.out" 2>&1; then
    match=$((match + 1))
  else
    echo "  DRIFT: $cu differs from re-emission:"
    sed 's/^/        /' "$EMITTMP/diff.out"
    emit_fail=1
  fi
done
echo "        $match/$total .cu match"
if [ "$total" -eq 0 ]; then
  echo "  FAIL: no committed cuda-out/*.cu samples found"
  fail=1
elif [ "$emit_fail" -ne 0 ]; then
  echo "  FAIL: emission drift ($match/$total match)"
  fail=1
else
  echo "  PASS: emission golden ($match/$total match)"
fi

# ---------------------------------------------------------------------------
echo "=================================================================="
if [ "$fail" -eq 0 ]; then
  echo "GATE: PASS  (corpus clean, census $n_gpu+$n_het, emission $match/$total)"
  exit 0
else
  echo "GATE: FAIL  (see the offending paths/diffs above)"
  exit 1
fi
