(****************************************************************************)
(*                           the diy toolsuite                              *)
(*                                                                          *)
(* HetLitmus: the oracle CSV's PROVENANCE grade.  See hetOracle.mli for the  *)
(* contract and env-research/PORT2-R2-amd-oracle.md 2.3 / 9.2 for the design.*)
(*                                                                          *)
(* This software is governed by the CeCILL-B license under French law.      *)
(****************************************************************************)

(* WHY THE GRADE COMES FROM THE ORACLE CSV AND NOT FROM THE CONTROL MAP.
   control-map-amd.csv is GENERATED by hetlitmus/verify/controlmap.py and
   re-derived from scratch by amdordercheck.py phase 9 (memo 9.4 G11), which
   compares it cell-for-cell against that fresh derivation.  A sixth column
   would have to be invented by the generator and taught to the gate.  Memo 9.2
   put the grade in expected-amd.csv, and that is where it is read from.

   THE VERDICT AND THE GRADE ARE TWO DIFFERENT CLAIMS and this module deals
   only with the second.  het_oracle (Disallowed / Allowed / NO-ORACLE) picks
   WHICH sentence the harness prints; the grade caps HOW STRONG that sentence
   is allowed to be.  Memo 2.0, amended and confirmed by Nguyen 2026-08-02:

     "a single-key derivation MAY be Disallowed, but it MUST carry declared
      single-chain provenance, and that declaration CAPS the reported claim
      strength: a mismatch on such a row indicts the oracle row first, never
      the CMCM."

   MEASURED on the shipped expected-amd.csv (2026-08-03):
     grades  318 derived + 46 herd7-checked + 32 artifact + 15 decision = 411
     of the 146 Disallowed rows, 32 carry `artifact' and 114 are CAPPED.
   So the capped path is the COMMON one, and a printer that cannot tell the two
   apart overstates 114 rows out of 146. *)

type t = {
    tbl : (string, string) Hashtbl.t ;   (* test -> raw grade string *)
    has_prov : bool ;                    (* the 5-column header was present *)
    src : string ;                       (* "<csv>:<model>" for the printout *)
  }

let trim s =
  let n = String.length s in
  let i = ref 0 and j = ref (n-1) in
  let sp c = c = ' ' || c = '\t' || c = '\r' in
  while !i < n && sp s.[!i] do incr i done ;
  while !j >= !i && sp s.[!j] do decr j done ;
  String.sub s !i (!j - !i + 1)

let load ~verbose ~dir ~csv ~model ~src_name =
  let tbl = Hashtbl.create 512 in
  let has_prov = ref false and found = ref false in
  let f = Filename.concat dir csv in
  (try
     let ch = open_in f in
     found := true ;
     (try
        while true do
          let line = input_line ch in
          if String.length line > 0 && line.[0] <> '#' && trim line <> "" then
            match String.split_on_char ',' line with
            | name :: rest ->
               let name = trim name in
               if name = "Litmus" then begin
                 (* DETECTED, NEVER ASSUMED -- the same rule oracle-compare.sh
                    applies at :88-92.  expected-nvidia.csv's header is the
                    4-column "Litmus,Expected,Model,Source" and 38 of its rows
                    carry commas INSIDE that free-text field, so reading field 4
                    as a grade there would invent grades out of prose. *)
                 match rest with
                 | _exp :: _mdl :: p :: _ when trim p = "Provenance" ->
                    has_prov := true
                 | _ -> ()
               end else begin
                 (match rest with
                  | _exp :: mdl :: _ ->
                     let mdl = trim mdl in
                     (* A harness tagged from the OTHER vendor's oracle is a
                        build bug that would silently produce confident
                        nonsense, so it is fatal rather than warned about.
                        Reachable only by pointing a lane at the wrong file. *)
                     if mdl <> model then
                       Warn.fatal
                         "hetlitmus: %s row %s carries Model %S, but this CPU \
                          ISA's lane expects %S.  The harness would be tagged \
                          from the wrong vendor's oracle."
                         csv name mdl model
                  | _ -> ()) ;
                 match rest with
                 | _exp :: _mdl :: p :: _ when !has_prov ->
                    Hashtbl.replace tbl name (trim p)
                 | _ ->
                    (* Row present, grade not readable: recorded as present so
                       prov_name can say NO-COLUMN rather than ABSENT. *)
                    Hashtbl.replace tbl name ""
               end
            | [] -> ()
        done
      with End_of_file -> ()) ;
     close_in ch
   with Sys_error _ ->
     if verbose >= 0 then
       Printf.eprintf
         "HetLitmus WARNING: no %s next to %s -- every harness emitted here \
          carries PROV_UNSET, so a mismatch on a Disallowed test will print as \
          UNGRADED and license no claim about the model.  This is fail-closed, \
          not a result.\n%!"
         csv src_name) ;
  { tbl ;
    has_prov = !has_prov ;
    src = if !found then Printf.sprintf "%s:%s" csv model else "(no oracle CSV)" }

(* THE GRADE -> CLAIM-STRENGTH MAP.  Memo 2.3's five grades, and memo 2.0's
   "full-strength reporting is licensed IFF the grade is artifact".

   `artifact-csv-corrected' is CAPPED, not full: memo 2.3 row 2 defines it as a
   row whose cited artifact cell THIS MEMO OVERTURNS, i.e. a derivation
   outranking an anchor under the 2.0a policy.  That is one instrument, not
   two.  It has 0 corpus rows today (it appears only in the generator's anchor
   table), so the mapping is unreachable from the shipped CSV and is written
   down for the direction it fails in, not for its census.

   `herd7-checked' is CAPPED and never reaches a Disallowed row at all (memo
   2.3: the only sound direction is Sometimes => Allowed), so it can only ever
   appear under a frame that makes no refutation claim.  Mapped anyway: a grade
   silently falling through to UNSET would read as corruption. *)
let enum_of_grade = function
  | "artifact" -> "PROV_ARTIFACT"
  | "derived" | "decision" | "herd7-checked" | "artifact-csv-corrected" ->
     "PROV_CAPPED"
  | _ -> "PROV_UNSET"

let prov_enum t name =
  match Hashtbl.find_opt t.tbl name with
  | None -> "PROV_UNSET"                     (* absent row: fail closed *)
  | Some g -> enum_of_grade g

let prov_name t name =
  match Hashtbl.find_opt t.tbl name with
  | None -> "ABSENT"
  | Some g ->
     if not t.has_prov then "NO-COLUMN"
     else if enum_of_grade g = "PROV_UNSET" then "UNKNOWN:" ^ g
     else g

let source t = t.src
let has_provenance t = t.has_prov
