#!/usr/bin/env bash
# The CPU-only positive control: six shapes (MP, LB, SB, 2+2W, R, IRIW)
# rendered as het tests whose every proc is tagged `cpu', generated into OUTDIR
# (never the repo).
#
#   usage:  ./generate-cpuonly.sh OUTDIR
#
# What the set buys, what each row must show, and why a sighting here is a
# finding about the host's x86-TSO conformance rather than about the compound
# model: hetlitmus/docs/positive-control.md, "The CPU-only set".
#
# A het test rather than an upstream X86_64 one, and that is the whole point: a
# plain litmus7 X86 run allocates x and y with litmus7's own allocator, while
# the question here is whether the SHARED allocation is write-back cacheable.
# The het harness reaches it through gd_alloc_shared (HET_ALLOC /
# hipMallocManaged), runs the same stress and prints the same verdict
# machinery.  The emitter classifies procs by their device tag and sets
# `_rec.cpu_only = 1' when every one of them is a CPU proc, so nothing here
# depends on the file name saying "cpuonly".
#
# Treat the 2+2W row as unresolved: it is the one store-only shape here, so its
# cycle is reconstructed by an observer whose scan matches store ids across
# iterations, where the coherence order it witnesses is defined within one.
# The four shapes with a real reader are unaffected (positive-control.md).
set -e
# OUTDIR is resolved against the caller's cwd BEFORE the `cd' below moves us, so
# a relative path -- what the Makefile caller passes -- is correct.  The same
# rule generate.sh and generate-x86.sh state at this spot.
OUT="${1:?usage: generate-cpuonly.sh OUTDIR}"
mkdir -p "$OUT"
OUT="$(cd "$OUT" && pwd)"

cd "$(dirname "$0")"
HETDIR="$(pwd)"
# shellcheck source=../../paths.sh
source ../../paths.sh
COMMON="-set-libdir $HERDLIB -bell $HETL/bells/ptx.bell"

[ "$OUT" != "$HETDIR" ] || { echo "refusing to write into the committed corpus" >&2; exit 2; }

# shape | nprocs | cycle
#
# The harnesses carry no verdict, and this script supplies none: comparing an
# observation against an oracle is the offline step (hetlitmus/oracle-compare.sh),
# over a CSV the caller brings.  Whatever a run shows, it is not a compound-model
# result: the CPU-only branch of het_verdict.h outranks the ordinary sentence,
# because on an all-CPU cycle the compound model is not under test.
CPUONLY_ROWS="
MP:2:PodWW Rfe PodRR Fre
LB:2:PodRW Rfe PodRW Rfe
SB:2:PodWR Fre PodWR Fre
2+2W:2:PodWW Coe PodWW Coe
R:2:PodWW Coe PodWR Fre
IRIW:4:Rfe PodRR Fre Rfe PodRR Fre
"

# The Layer-B canary for this set, rather than the het MP canary the main corpus
# uses: what a null here needs vouched for is the SHARED allocation's store
# buffer, and only a CPU-only Allowed shape on that allocation vouches for it
# (hetlitmus/docs/positive-control.md, "The CPU-only set").
CANARY="SB-cpuonly-x86_64"

CM="$OUT/control-map-amd.csv"
cat > "$CM" <<EOF
# HetLitmus CPU-only positive control -- control map.  GENERATED by
# generate-cpuonly.sh; do not hand-edit.
# Mu is \`none' on every row by DERIVATION, not for want of a candidate: an x86
# rendering of these cycles is plain MOVs with no fence, already at the bottom of
# the x86 strength lattice, so every null here is a weak null vouched for by the
# Layer-B canary ($CANARY) alone.
Test,Mu,MuRule,MuAlt,MuRelaxed,Canary
EOF

n=0
printf '%s\n' "$CPUONLY_ROWS" | while IFS=: read -r shape nprocs cycle; do
  [ -n "$shape" ] || continue
  name="$shape-cpuonly-x86_64"
  devs="cpu"; i=1
  while [ "$i" -lt "$nprocs" ]; do devs="$devs,cpu"; i=$((i+1)); done
  # -gpu is a required option of hetgen7 and is unused here: no proc carries the
  # gpu tag, so no LISA column is rendered.  It is fed the same cycle so the two
  # arguments cannot drift apart into a cycle mismatch.
  "$BIN/hetgen7" $COMMON -cpu-arch x86_64 -devices "$devs" -name "$name" \
    -cpu "$cycle" -gpu "$cycle" > "$OUT/$name.litmus"
  # Sanity: every proc really is tagged x86_64 and none is a gpu column.  Cheap,
  # and it is the property the whole CPU-only reading rests on.
  if grep -qE 'P[0-9]+:gpu' "$OUT/$name.litmus"; then
    echo "FAIL: $name has a gpu column -- it is not a CPU-only test" >&2; exit 1
  fi
  if [ "$name" = "$CANARY" ]; then can="self"; else can="$CANARY"; fi
  echo "$name,none,at the lattice floor (plain MOVs; no fence) -- Layer-B canary only,-,none,$can" >> "$CM"
done

n="$(ls "$OUT"/*.litmus | wc -l)"
echo "generate-cpuonly: $n CPU-only tests + control-map-amd.csv in $OUT"
[ "$n" -eq 6 ] || { echo "FAIL: expected 6 CPU-only tests, found $n" >&2; exit 1; }
# The map must key the set exactly, in both directions -- the same check
# generate-x86.sh makes, and for the same reason: a test with no row is refused
# by the emitter, so the whole set would stop rather than emit a harness that
# co-runs nothing.
ls "$OUT"/*.litmus | sed 's|.*/||; s|\.litmus$||' | sort > "$OUT/.keys.tests"
m=control-map-amd.csv
awk -F, '!/^#/ && NF>1 && $1 != "Test" { print $1 }' \
  "$OUT/$m" | sort > "$OUT/.keys.$m"
diff -q "$OUT/.keys.$m" "$OUT/.keys.tests" >/dev/null || {
  echo "FAIL: $m does not key the CPU-only set exactly:" >&2
  diff "$OUT/.keys.tests" "$OUT/.keys.$m" >&2; exit 1; }
rm -f "$OUT/.keys.$m" "$OUT/.keys.tests"
