// ======================================================================
// CUDA litmus test: MP-sys-F
// Generated by HetLitmus CudaLang from a LISA/Bell scoped test.
// DO NOT EDIT -- regenerate via hetlitmus/emit-cuda.sh
//
// LISA source program:
//   P0: w[relaxed,sys] x 1
//   P0: w[release,sys] y 1
//   P1: r[acquire,sys] r0 y
//   P1: r[relaxed,sys] r1 x
// scopes: (sys (gpu (cta 0) (cta 1)))
// condition: exists (1:r0=1 /\ 1:r1=0)
// launch: <<<2, 1>>>  (2 CTA(s), 1 thread(s)/CTA)
// ======================================================================

#include <cuda/atomic>
#include <cstdio>

__global__ void litmus_MP_sys_F(int* x, int* y, int* __out) {
  // ---- P0  (CTA 0, lane 0) ----
  if (blockIdx.x == 0 && threadIdx.x == 0) {
    { // w[relaxed,sys] x 1
      cuda::atomic_ref<int, cuda::thread_scope_system> ref(*x);
      ref.store(1, cuda::memory_order_relaxed);
    }
    { // w[release,sys] y 1
      cuda::atomic_ref<int, cuda::thread_scope_system> ref(*y);
      ref.store(1, cuda::memory_order_release);
    }
  }

  // ---- P1  (CTA 1, lane 0) ----
  if (blockIdx.x == 1 && threadIdx.x == 0) {
    int r0 = 0;
    int r1 = 0;
    { // r[acquire,sys] r0 y
      cuda::atomic_ref<int, cuda::thread_scope_system> ref(*y);
      r0 = ref.load(cuda::memory_order_acquire);
    }
    { // r[relaxed,sys] r1 x
      cuda::atomic_ref<int, cuda::thread_scope_system> ref(*x);
      r1 = ref.load(cuda::memory_order_relaxed);
    }
    __out[1 * 4 + 0] = r0;
    __out[1 * 4 + 1] = r1;
  }
}

// ---- host harness (illustrative) ----
// Result buffer layout: __out[proc * 4 + regIndex].
// Reset all globals to 0 before each launch; the weak outcome under
// test is exactly the `condition' line above.
int main(void) {
  int *x;   cudaMallocManaged(&x, sizeof(int));
  int *y;   cudaMallocManaged(&y, sizeof(int));
  int *__out; cudaMallocManaged(&__out, sizeof(int) * 2 * 4);
  for (int it = 0; it < 100000; ++it) {
    *x = 0;
    *y = 0;
    litmus_MP_sys_F<<<2, 1>>>(x, y, __out);
    cudaDeviceSynchronize();
    // TODO(hardware): tally __out against the condition.
  }
  return 0;
}
