// ======================================================================
// CUDA litmus test: SB-sys
// Generated by HetLitmus CudaLang from a LISA/Bell scoped test.
// DO NOT EDIT -- regenerate via hetlitmus/emit-cuda.sh
//
// LISA source program:
//   P0: w[relaxed,sys] x 1
//   P0: r[relaxed,sys] r0 y
//   P1: w[relaxed,sys] y 1
//   P1: r[relaxed,sys] r0 x
// scopes: (sys (gpu (cta 0) (cta 1)))
// condition: exists (0:r0=0 /\ 1:r0=0)
// launch: <<<2, 1>>>  (2 CTA(s), 1 thread(s)/CTA)
// ======================================================================

#include <cuda/atomic>
#include <cstdio>
#include <cstdlib>

__global__ void litmus_SB_sys(int* x, int* y, int* __out) {
  // ---- P0  (CTA 0, lane 0) ----
  if (blockIdx.x == 0 && threadIdx.x == 0) {
    int r0 = 0;
    { // w[relaxed,sys] x 1
      cuda::atomic_ref<int, cuda::thread_scope_system> ref(*x);
      ref.store(1, cuda::memory_order_relaxed);
    }
    { // r[relaxed,sys] r0 y
      cuda::atomic_ref<int, cuda::thread_scope_system> ref(*y);
      r0 = ref.load(cuda::memory_order_relaxed);
    }
    __out[0 * 4 + 0] = r0;
  }

  // ---- P1  (CTA 1, lane 0) ----
  if (blockIdx.x == 1 && threadIdx.x == 0) {
    int r0 = 0;
    { // w[relaxed,sys] y 1
      cuda::atomic_ref<int, cuda::thread_scope_system> ref(*y);
      ref.store(1, cuda::memory_order_relaxed);
    }
    { // r[relaxed,sys] r0 x
      cuda::atomic_ref<int, cuda::thread_scope_system> ref(*x);
      r0 = ref.load(cuda::memory_order_relaxed);
    }
    __out[1 * 4 + 0] = r0;
  }
}

// ---- host harness (illustrative) ----
// Result buffer layout: __out[proc * 4 + regIndex].
// Reset all globals to 0 before each launch; the weak outcome under
// test is exactly the `condition' line above.
static void alloc_checked(void** p, size_t bytes, const char* what) {
  *p = NULL;
  cudaError_t e = cudaMallocManaged(p, bytes);
  if (e != cudaSuccess || *p == NULL) {
    fprintf(stderr, "HetLitmus FATAL: cudaMallocManaged of %llu bytes for %s failed (%s)\n",
            (unsigned long long)bytes, what, cudaGetErrorString(e));
    exit(2);
  }
}

int main(void) {
  int *x;   alloc_checked((void**)&x, sizeof(int), "x");
  int *y;   alloc_checked((void**)&y, sizeof(int), "y");
  int *__out; alloc_checked((void**)&__out, sizeof(int) * 2 * 4, "__out");
  for (int it = 0; it < 100000; ++it) {
    *x = 0;
    *y = 0;
    litmus_SB_sys<<<2, 1>>>(x, y, __out);
    cudaDeviceSynchronize();
  }
  return 0;
}
